info:
  version: 1.0.0

spring:
  application:
    name: HelloServer
  cloud:
    inetutils:
      default-hostname: hello.server

server:
  port: 7111

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.5.181:8761/eureka,http://10.20.0.61:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
#    ip-address: 192.168.6.132
    hostname: hello.server
    # 本地有虚拟机网卡会导致windows一直获取的是localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

feign:
  hystrix:
    enabled: true
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
    connection-timeout: 2000
  compression:
    request:
      enabled: true
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: true
    hystrix:
      config:
        default:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 2000
logging:
  level:
    com:
      netflix: debug